### ISSUE TITLE
Displays events in different timezones as if in the same timezone

### ISSUE THREAD

**Issue by wilbowma** [danstowell/calendrino#6]
If an .ics file contains event in two different timezones, it displays both in their original timezone, resulting in an incorrect view of the calendar. For example, if a calendar contains an event in 4pm PST and 4pm GMT+1, these both display as at "4pm".

Probably one would want an option in the HTML UI to select a timezone, but a more expedient solution might be to specify a timezone in the call to calendrino.

**Comment by danstowell** [comment]
Thanks - can you confirm which version of the code you're using? I've been working on adding timezone support in April-May this year, and so far it works for me.

Timezones can be mind-bending to code for, though. If you have a minimal simplified ICS file that exhibits the problem, that would help.

**Comment by wilbowma** [comment]
Oh it might be that I haven't updated recently; I'll take another look and if it persists, upload an .ics.

**Comment by wilbowma** [comment]
Updating Calendrino fixed the problem; thanks!
